--liquibase formatted sql

--changeset vikhtiiarov:1
CREATE TABLE IF NOT EXISTS user_ads
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    user_name TEXT            NOT NULL,

    password TEXT             NOT NULL,

    first_name TEXT           NOT NULL,

    last_name TEXT            NOT NULL,

    phone TEXT                ,

    email TEXT                NOT NULL,

    image TEXT                ,

    role TEXT                  NOT NULL
);

CREATE TABLE IF NOT EXISTS ads
(
    pk INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    author INTEGER NOT NULL REFERENCES user_ads(id),

    price INTEGER NOT NULL ,

    first_name TEXT NOT NULL ,

    title TEXT NOT NULL ,

    description TEXT ,

    image TEXT
);

CREATE TABLE comment
(
    ad_id INTEGER NOT NULL REFERENCES ads(pk),

    author INTEGER NOT NULL REFERENCES user_ads(id),

    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY ,

    created_at BIGINT NOT NULL ,

    text TEXT,

    PRIMARY KEY (ad_id,comment_id)

)

--changeset dKarpov:1
ALTER TABLE ads DROP COLUMN first_name;

CREATE TABLE IF NOT EXISTS image
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filePath TEXT,
    fileSize BIGINT,
    mediaType TEXT
);

--changeset dKarpov:2
ALTER TABLE ads ALTER COLUMN image TYPE INTEGER USING 0;
ALTER TABLE ads ADD FOREIGN KEY (image) REFERENCES image(id);

ALTER TABLE user_ads ALTER COLUMN image TYPE INTEGER USING 0;
ALTER TABLE user_ads ADD FOREIGN KEY (image) REFERENCES image(id);

--changeset dKarpov:3
ALTER TABLE image RENAME COLUMN filepath TO file_path;
ALTER TABLE image RENAME COLUMN fileSize TO file_size;
ALTER TABLE image RENAME COLUMN mediaType TO media_type;

--changeset dKarpov:4
ALTER TABLE image ADD COLUMN IF NOT EXISTS url TEXT;

--changeset dKarpov:5
ALTER TABLE comment DROP CONSTRAINT comment_pkey;
ALTER TABLE comment ADD PRIMARY KEY (comment_id);
