--liquibase formatted sql

--changeset vikhtiiarov:1
CREATE TABLE IF NOT EXISTS user_ads
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    user_name TEXT            NOT NULL,

    password TEXT             NOT NULL,

    first_name TEXT           NOT NULL,

    last_name TEXT            NOT NULL,

    phone TEXT                ,

    email TEXT                NOT NULL,

    image TEXT                ,

    role TEXT                  NOT NULL
);

CREATE TABLE IF NOT EXISTS ads
(
    pk INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    author INTEGER NOT NULL REFERENCES user_ads(id),

    price INTEGER NOT NULL ,

    first_name TEXT NOT NULL ,

    title TEXT NOT NULL ,

    description TEXT ,

    image TEXT
);

CREATE TABLE comment
(
    ad_id INTEGER  GENERATED BY DEFAULT AS IDENTITY REFERENCES ads(pk),

    author INTEGER NOT NULL REFERENCES user_ads(id),

    comment_id INTEGER NOT NULL ,

    created_at BIGINT NOT NULL ,

    text TEXT,

    PRIMARY KEY (ad_id,comment_id)

)



