--liquibase formatted sql

--changeset vikhtiiarov:1
CREATE TABLE ads
(
    pk INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    autor INTEGER NOT NULL ,

    price INTEGER NOT NULL ,

    first_name TEXT NOT NULL ,

    title TEXT NOT NULL ,

    description TEXT ,

    image TEXT
);

CREATE TABLE user_ads
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    user_name TEXT            NOT NULL,

    password TEXT             NOT NULL,

    first_name TEXT           NOT NULL,

    last_name TEXT            NOT NULL,

    phone TEXT                NOT NULL,

    email TEXT                NOT NULL,

    image TEXT                NOT NULL,

    role TEXT                  NOT NULL
);

CREATE TABLE comment
(
    ad_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    autor INTEGER NOT NULL ,

    comment_id INTEGER NOT NULL ,

    created_at BIGINT NOT NULL ,

    text TEXT

)